### ISSUE TITLE
Verwijder repo/reupload

### ISSUE THREAD

**Issue by karelvanhecke** [Dyvex/ProjectenIII---Linux---1920#11]
Sommige commits zijn gelinkt aan onze persoonlijke emails. Om te verkomen dat bots die emails scrapen, de repo verwijderen en als je wil kan je hem reuploaden na de .git directory te verwijderen en opnieuw te initaliseren met git init. Dan heb je de files weer op github zonder onze commits.

**Comment by Dyvex** [comment]
Oke, zal ik zodadelijk doen.
